GET https://localhost:5001/api/users
Accept: application/json

###



POST https://localhost:5001/api/users/updateEmail
Content-Type: application/json

{
  "oldEmail": "somemail2@user.dk",
  "newEmail": "hello@user.dk"
}

###

POST https://localhost:5001/api/users/UpdateUsername
Content-Type: application/json

{
  "email": "otheruser@user.dk",
  "newUsername": "MyNewUsername"
}

###

// Update email
POST https://localhost:5001/api/users/Update
Content-Type: application/json

{
  "UpdateReason": 0,
  "originalEmail": "otheruser@user.dk",
  "updatedEmail": "otheruser@user.dk"
}

###

// Update username
POST https://localhost:5001/api/users/Update
Content-Type: application/json

{
  "UpdateReason": 1,
  "originalEmail": "otheruser@user.dk",
  "updatedUsername": "someuser"
}

###

// Update email using the dynamic command dispatcher
POST https://localhost:5001/api/users/UpdateEmailWithDispatcher
Content-Type: application/json

{
  "OldEmail": "otheruser@user.dk",
  "NewEmail": "somenewemail@user.dk"
}

###